### ISSUE TITLE
Inhibition 

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#10]
`Inhibition` should be added to the data model.

this either goes in `AssayMethod` or `Measurement`.

**Comment by cmangat** [comment]
I think it goes in both.  The method of inhibition detection is specific to the method and a reported measurement.

**Comment by hswerdfe** [comment]
So, like does that mean we duplicate the data? or 
do we add something like `inhibitionDefault` to `assayMethod` then pull the default when the new measurement is made?
