### ISSUE TITLE
Add sampleID to SiteMeasure

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/covid-19-wastewater#102]
Add a list of samples that correspond to a SiteMeaure.

Considerations:
- There may be multiple samples that correspond to a SiteMeasure.
- How best to collect in different formats like Excel spreadsheets? This is an implementation issue but worthwhile considering.

**Comment by vipileggi** [comment]
@DougManuel  yes adding sampleID to SiteMeasure would work as long as the sampleID are kept unique. For the first labs that have reported data so far they're keeping it unique.

**Comment by NielsNicolai** [comment]
I'm still in the opinion that the corresponding samples can always be traced back using the date and time of the SiteMeasure. Is that not enough?

**Comment by hswerdfe** [comment]
@NielsNicolai I agree with you in principle, MECP did have some issues with this, so we agreed to add it in.
