### ISSUE TITLE
Sample index

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/covid-19-wastewater#103]
The `Sample` table does not efficiently describe replicate samples. For example, when you take multiple grab samples on the same day at the same location. Therefore I would suggest adding an `index` field to this table, similar to the one in the `WWMeasure` table.

**Comment by vipileggi** [comment]
@NielsNicolai yes agree but the experience from MECP is that this index is not being used properly and we need some other built in key(s) as a redundant way to get this information when we aggregate the worksheets.

**Comment by NielsNicolai** [comment]
Hi @vipileggi, how is it used at the moment? 
One way of dibble checking whether it's a replicate or not is by validating if the date, site and type combination already exists. Yet this can only be done in the data validation/post-processing I think.

**Comment by NielsNicolai** [comment]
Included with this [commit](https://github.com/Big-Life-Lab/covid-19-wastewater/commit/21525dfeea7cf86a58cf6c0126cc5ddb23f97e9b)

**Comment by vipileggi** [comment]
Hi @NielsNicolai  on https://github.com/Big-Life-Lab/covid-19-wastewater/issues/103#issuecomment-789652566 
that is what I've done as a temporary hack or workaround but not ideal. We had some MECP internal discussion on this and decided to try and communicate back to the users to clarify the use of the **index** variable and still necessary and can't think of a better way at the moment.
