### ISSUE TITLE
InstrumentID for the Sample table

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/covid-19-wastewater#104]
My colleagues have provided me with some technical information on how the autosamplers work. They wanted to add that to the data model, yet they noticed that there is no InstrumentID for a sample. I think it would make sense to also add it to the Sample table.

**Comment by vipileggi** [comment]
@NielsNicolai agree a good idea to validate sample collection process.

**Comment by NielsNicolai** [comment]
Done with this [commit](https://github.com/Big-Life-Lab/covid-19-wastewater/commit/e1121c6ff44fd7c8dcce6b3ef61300a18f68c71c)
