### ISSUE TITLE
auto generate the ERD

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#106]
auto generate the `erd` from the table files and or the outputted database using [datamodelr](https://github.com/bergant/datamodelr)

It would not look the same but it would be easier to keep things in sync.

looking for advise on this???

**Comment by hswerdfe** [comment]
Option for what an auto generated ERD may look like keys only.

![image](https://user-images.githubusercontent.com/19482839/109655127-eb399c00-7b30-11eb-89dd-060f1ca8ea6c.png)

**Comment by hswerdfe** [comment]
another options for auto generated ERD with everything showing.

![image](https://user-images.githubusercontent.com/19482839/109655305-2045ee80-7b31-11eb-86d7-d87d9c1a111b.png)

**Comment by hswerdfe** [comment]
there is an option in the package to have arrows pointing to the columns but it isn't perfect see example.

![image](https://user-images.githubusercontent.com/19482839/109658672-dced7f00-7b34-11eb-89ec-60504dd5a71f.png)

**Comment by DougManuel** [comment]
The second diagram works best for me, but the third is also pretty good.

**Comment by NielsNicolai** [comment]
@hswerdfe from which file is this generated?

**Comment by hswerdfe** [comment]
@NielsNicolai the R file is in `src/generate_db_generations_sql.R`, the function is `wbe_generate_erd()` the files it uses for content are `Tables.csv` and `Variables.csv` the R package used is `https://github.com/bergant/datamodelr`

**Comment by hswerdfe** [comment]
@DougManuel the second is my least favorite as the arrows seem to point to a random spot on the table, and not the column that is the `foreign` key

**Comment by NielsNicolai** [comment]
@hswerdfe Thanks for clarifying, and good to know that it is already being generated using the `.csv` files.

If not the second, I prefer the first one. But it doesn't really compare as not all variables are included at this point.

**Comment by hswerdfe** [comment]
@NielsNicolai  there is an option when drawing with the `datamodelr` package to only draw the keys, that is what the first one is doing.
