### ISSUE TITLE
Add 'publicHealthUnit' to 'Site' table

### ISSUE THREAD

**Issue by vipileggi** [Big-Life-Lab/covid-19-wastewater#112]
To simplify aggregating and sorting data by way of the MECP Templates being uploaded to the ArcGIS Hub for MECP we would benefit from the additional column of `publicHealthUnit` on `Site` table. This would allow us to filter the sites easier if this is included and especially since in some cases the labs leave the coordinates fields blank.

**Comment by hswerdfe** [comment]
`PublicHealthData` data can be linked to `Site` with the `Polygon` table as a go between. this intermediate was done because it was thought that not all reporting would be one to one on drainage area and PH summary.

**Comment by vipileggi** [comment]
@hswerdfe https://github.com/Big-Life-Lab/covid-19-wastewater/issues/112#issuecomment-790708349 right but the Ontario Template does not have a `Polygon` table at this time. Reason, as I recall, is that the MECP Geomatics group felt they can collect that data separately and thus minimize user burden. Not sure, will check, if the plan is to integrate the `Polygon` data into the master aggregated MECP data set stored on ArcGIS Hub, accessible by PHAC and others.

**Comment by hswerdfe** [comment]
I had envisioned the `Site` table being reported by a different entity then the `PublicHealthData` anyway.

**Comment by vipileggi** [comment]
@hswerdfe yes, it seems that a single reporter is collating and inputting the data from their direct sources.  I can add this to the `Site`  table (assigned it to myself) and make a PR if you agree. I've also tagged it for discussion (@DougManuel @NielsNicolai  @jeandavidt ) and was hoping we can include this to  V1.10 since MECP wants to distribute the next version of the Ontario Template soon.

**Comment by DougManuel** [comment]
Addressed in V1.1.0.

However, would benefit from a look-up table. Will open new issue for 1.2.0.

**Comment by DougManuel** [comment]
See #118.
