### ISSUE TITLE
create an data upload template

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#13]
Create a template file that is flat and wide, and easy for labs to enter data into, but also easy to etl.

**Comment by DougManuel** [comment]
Ready to add to this repo? suggest a 'template' folder.

**Comment by hswerdfe** [comment]
agreed on the template folder.
does the template stay in excel?

I was thinking we could provide an excel template, link to a google sheets template, and a txt template.

p.s. I think you can feel free to upload the current template as is.

**Comment by hswerdfe** [comment]
errr, I mean as is with the required data deleted ... :)

**Comment by DougManuel** [comment]
Changing the label to v1.0. Template from MECP uploaded.
