### ISSUE TITLE
suggest reporting both the PMMoV Ct value and PMMoV copies/X amount of sludge

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#14]
Received this comment 

> The amount of sample loaded in qPCR plates might vary from lab to lab and so reporting only PMMoV Ct value when working with sludge will not allow quick comparison between studies (one would need to look into individual methods and adjust all data). If comparison of pepper level in sludge is something of interest, I would suggest reporting both the PMMoV Ct value and PMMoV copies/X amount of sludge to allow for direct comparison.

I need to think about if we are currently able to do this.

**Comment by DougManuel** [comment]
Labs that report sludge use viral copies/copies of PPMV. 

There is interest in reporting measures to adjust for total flow but these have not yet widely discussed or reported. 

Closing for now. Feel free to reopen.
