### ISSUE TITLE
move laboratory table to connect with sample table

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#2]
while often a site will use the same lab, lab is technically, one to many with  testresults. As  different labs can analyses the same "sub-sample".

**Comment by DougManuel** [comment]
Yes. This was brought up in discussions with labs but it was felt that practically this doesn't happen. However, we will update to keep this provision.

**Comment by hswerdfe** [comment]
You could link lab and method to both site and results table, then when data is uploaded lab is optional on the results, and you take the "default" labid
