### ISSUE TITLE
ETL - script wide to long

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#20]
Create a generic ETL tool that transforms forms any data from the generic wide structure to the generic long format.

**Comment by hswerdfe** [comment]
script should assume template data is in format

`Table`.`field`
and that the `_` is used as a separator in the measures table.

**Comment by DougManuel** [comment]
Also from long to wide.

**Comment by hswerdfe** [comment]
this was done with last checking
