### ISSUE TITLE
Can this format assist with inter lab verification

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#22]
Can this format assist with inter lab verification.

IE can it work based on sub-samples or a model matrix across different labs.

**Comment by DougManuel** [comment]
I think it should work now. One sampleID can have multiple measurements, labID, assayID, analysisDate, etc.

**Comment by hswerdfe** [comment]
Perfect, Thanks @DougManuel. you are correct. I will close.
