### ISSUE TITLE
Sewer Trucks and Airplanes

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#23]
Sewer Trucks and Airplanes, need to be able to be fit in this model

**Comment by DougManuel** [comment]
There is `siteType` `other` with `siteTypeOther`. I had envisioned that when `other` was filled out, then a new category would be added.

That stated, I wondered if we should add another variable to capture setting. `siteSetting` which could have categories such as: municipal residential, long-term care facility, post-secondary education resident, business, etc. truck and airplane could go here.

**Comment by hswerdfe** [comment]
I agree `siteType` fits fine for sewage truck or airplane. 
but some of the other features do not apply. Like lat,long and polygon.
I think it is ok for now and sewer truck details can be added to the site notes.

I like your idea about `siteSetting` as i think currently this would need to go in notes but categorical is for sure better for something like this.
Can I propose different name though something like `primarySourceOfWastewater` with all the categories you listed?

**Comment by DougManuel** [comment]
OK. I'll tag for the to-do list.

**Comment by DougManuel** [comment]
See commit https://github.com/Big-Life-Lab/covid-19-wastewater/commit/2e0c8823b5d2b9eb57055a92d477efbb225f9077

- new variable added to SQL but not ERD (yet).
