### ISSUE TITLE
pH COD Temp

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#24]
Add some WWTP parameters. pH, COD, Temp of ww

**Comment by DougManuel** [comment]
Does this go in sample metadata or site metadata?

**Comment by hswerdfe** [comment]
these go in `Measurement`.`measureCat`. 
Just like `wwParamBod` only `wwParamCod` etc, and units need to be added as appropriate

**Comment by DougManuel** [comment]
I think that these go in the sample table, including the other ww parameters that are already there such as wwParamBod. 

These are attributes of the sample -- attributes that are taken at the time of the sample collection. Measurements are tests that are performed on the sample. Typically, measurements are performed in the lab.

**Comment by DougManuel** [comment]
See new table `siteMeasure`.
