### ISSUE TITLE
Time till cooling

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#25]
how long till the sample was cooled ?

**Comment by DougManuel** [comment]
And also if the sample was cooled at all. It is is not clear what to enter the current `sampleStorageTempC` if not cooling was performed.

**Comment by hswerdfe** [comment]
agreed,  I need a meeting with statscan who suggested this on friday, as it is recorded in their data . Once I understand what is actually in the statscan data I can mod the file format.

**Comment by DougManuel** [comment]
Moving discussion over to issue #62.
