### ISSUE TITLE
Site data should have optional start date and end date fields

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [Big-Life-Lab/covid-19-wastewater#26]
Site metadata should have optional start date and end date fields (which would allow multiple lines for the same site) in case sampling characteristics change over time (e.g., sampleType or assayMethod). This allows linkage between site data and sample data to indicate that different observations correspond to different sampling methods.

**Comment by DougManuel** [comment]
Good idea. Site metadata requires further development. We were aware that Site metadata could change, have multiple Labs, etc. but we were concerned about making the ERD and data structure too complicated for a first version. 

We will flag for discussion and update.

**Comment by hswerdfe** [comment]
I think this functionality already exists.

sampleType is in the Sample table. characteristics of the sampling mechanism can not only change over time but can change with each sample. assayMethod can change multiple times even for the same sample.

**Comment by jeanpaulrsoucy** [comment]
@hswerdfe I think you might be right on this specific point. I guess I was looking at the current version of data/wastewater_site.csv rather than the current SQL table.

On that note, though, the wastewater_site.csv has a field for catchmentPop which I don't see reflected anywhere in the SQL table. This is something that could conceivably change over time (e.g., on a yearly basis) and it is not the same thing as the population of the associated health region(s) (which I notice also do not have a field for population value). But maybe this is a separate issue.

**Comment by DougManuel** [comment]
Thanks, we've identified misalignment with the data and SQL table. 

@hswerdfe I set up the .md to reflect a metadata approach that other covid-19 aggregators use, but I now have some regrets that we didn't set up in more of a table format that could be used to generate the SQL, human document, etc.

Let's ponder migrating the metadata over to a proper table, object format. 

I'll make a separate issue and close this one. Feel free to reopen if needed.
