### ISSUE TITLE
separated  space for sample handling 

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#30]
After talking to Statscan about the data the data they have I wonder if a seperate table is needed for handling .....

**Comment by hswerdfe** [comment]
this can be addressed with multiple dates on the same wide table. and a few extra options on the measurements table

**Comment by cmangat** [comment]
Not sure what is meant by handling.

**Comment by hswerdfe** [comment]
duplicate of https://github.com/Big-Life-Lab/covid-19-wastewater/issues/34 


@cmangat  by handling I ment shipping. and particularly the need to take quality measures when it arrives in the lab, and maybe the temperature while shipping.
