### ISSUE TITLE
measurements taken on the same sample on different dates

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#32]
Currently the measurements that are taken on different dates do not fit into the suggested "wide" format of the table.
They do fit into the long format, but that is less intuitive.
as an example NML records some information about the state of the sample when it arives, then typically will process the sample the next day.

**Comment by hswerdfe** [comment]
@DougManuel a hack for a solution for the sample_measurement template where different measurements get done on different days  we can propose the following format
All sample data first on the left. 
then a date, then a list of formats taken on that date, then another date and a second list of measurements on that date.

**Comment by DougManuel** [comment]
If I follow your use case. Conceptually, the data model works, I think, even for labs or groups that transport, store and measure samples at different days and locations. The key is a single `sampleID` that has multiple measurements. 

Wide-format data still works, but not ideal. In a wide format data, there would be multiple rows with the same sampeID and missing measurements or values in early rows that reflect data collection but not measurement.

**Comment by cmangat** [comment]
We go through this often, especially with high-profile samples.  Repeat testing does happen.  Two results one sample.

**Comment by DougManuel** [comment]
Just restating my previous comment on Dec. 4 that the data model should work using multiple rows in a wide table format. 

That stated, we would benefit from a review of how different time points are captured throughout the measurement process. 

See https://github.com/Big-Life-Lab/covid-19-wastewater/issues/62.
