### ISSUE TITLE
can this model handle pooling data

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#33]

**Comment by hswerdfe** [comment]
mechanism for linking one sample to another sample.

**Comment by cmangat** [comment]
The pool would have to be its own sample.  Very relevant. One respondent will be pooling samples. As will Rob's group I've heard.

**Comment by hswerdfe** [comment]
duplicate of https://github.com/Big-Life-Lab/covid-19-wastewater/issues/34
