### ISSUE TITLE
DefaultAssayID

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#37]
working on the transformation script and I realized that the same lab that measures Viral copies per ml may also measure temperature of the sample. the defaultAssay, can't apply to temperature of sample.

So we would need another table, linking lab with measurement type, might look like this 

**LabDefaults**
 - `labID`
 - `measureCat`
 - `measureUnit`
 - `measureType`
 - `defaultAssay`

**Comment by DougManuel** [comment]
This takes us to the discussion about whether `Measurement` -- renamed `wwMeasure` should contain only viral measures. Note that we now have `siteMeasure` which contains measurements from the site of wastewater collection. `siteMeasure` includes information about instruments used to measure the data.

There seem to be three options:
1) Have three tables: `siteMeasure`, and then `wwMeasure` would be broken into two tables, something like `viralMeasures` and `otherMeasures`.
2) Continue what we have with other measures in WW not ideally captured.
3) We could consider a more generalized single table for measures - as discussed previously.

@NielsNicolai do you or your uLaval team have thoughts?

**Comment by DougManuel** [comment]
On the balance, it may make sense to add the following variables to `wwMeasures` that could be used for the `wq` measures. These variables are currently in `siteMeasure`. 

I am leaning towards a new object for `instrument` that would be analogous to `assayMethod`or we could add the concept of instrument to `assayMethod`. Meaning, `assayMethod` could describe how a viral measure or other measure (i.e. temperature) was performed.

-   **typeDescription**: Additional information on the performed measurement.

-   **instrumentName**: Name of the instrument used to perform the measurement.

-   **instrumentType**: Type of instrument used to perform the measurement.

    -   `online`: An online sensor.
    -   `lab`: Offline laboratory analysis.
    -   `handheld`: A handheld measurement analyzer.
    -   `atlineAnalyzer`: An atline analyzer with sampler.
    -   `other`: An other type of measurement instrument. Add description to `instrumentTypeOther`.

-   **instrumentTypeOther**: Description of the instrument in case it is not listed in `instrumentType`.

**Comment by DougManuel** [comment]
`Instrument` table created based on variables in `SiteMeasure` and `AssayMethod`. The `SiteMeaure` instrument variables were moved to the new table.
