### ISSUE TITLE
what is and is not a unit?

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#38]
creating a template for Chand at NML. 
He was telling me that PMMV is not a unit, so we might need to change that. These are the headers we found in his header, where headers are of the form

**measureCat_measureUnit_measureType**

 - `Measurement.covidN1_cycles_singleton_1`
 - `Measurement.covidN1_cycles_singleton_2`
 - `Measurement.covidN2_cycles_singleton_1`
 - `Measurement.covidN2_cycles_singleton_2`
 - `Measurement.mhv_cycles_singleton_1`
 - `Measurement.mhv_cycles_singleton_2`
 - `Measurement.PMMV_cycles_singlton_1`
 - `Measurement.PMMV_cycles_singlton_2`
 - `Measurement._notes`
 - `Measurement.covidN1_ml_singleton_1`
 - `Measurement.covidN1_ml_singleton_2`
 - `Measurement.PPMV_ml_singleton_1` 
 - `Measurement.PPMV_ml_singleton_2`

The ones of the machine are in units of `cycles` then once he normalizes by a standard curve they are in copies per ml. 

So in the end the issue is move ppmv out of `measureUnit` and into `measureCat`

**Comment by DougManuel** [comment]
Yes, there are inconsistencies with PMMV. 
For discussion:
1) PMMV should be in measureCat. 
2) PMMV should not be in measureUnit
3) PMMV should be in measureType as some sort of standardized or summary measure. Currently, in Ottawa the main measure reported is average N1 + N2 viral copies per PMMV viral copy. 

It could be argued that the viral copies/PMMV is not part of the metadata, but these are often the main measures that are reported. It could be a different section of how to name summary measures, but suggest it part of the metadata.

**Comment by hswerdfe** [comment]
Its getting complicated, and this doesn't even get into the batch normalization curves we need to make Chands first 8 curves useful.

**Comment by DougManuel** [comment]
We need to split up the task. For discussion:
1) Measurement.csv should focus on what is produced from the machines that generate viral load, PMMV and other metrics.
The machines report out means, SD, etc. 
2) Reporting metrics are another group of measures that are generated from Measurement.csv.
3) Normalization curves, QA metrics and process are another group of metrics. 

Suggest that we focus on (1) and (2) now. Keep in mind how (3) should be done.

**Comment by hswerdfe** [comment]
yah, that is what I told chand, but then the reporting metrics are basically calculated from the raw metrics and the normalization curves.

So he has no incentive to report the raw metrics, just the reporting metrics

**Comment by cmangat** [comment]
This is mostly because the reporting metrics are in flux (If I'm understanding the nomenclature). We are reporting data and concurrently developing best practices.
