### ISSUE TITLE
Method should connect with TestResult

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#4]
Method is 1 to many with TestResult

**Comment by DougManuel** [comment]
Will update.

**Comment by DougManuel** [comment]
Hmm, on reflection, I'm not sure and will leave open for discussion with labs. An assay method has different parts including sample collection and testing. 

This could be kept together or split into two different methods (sample and test) but that seems a bit complicated.

**Comment by hswerdfe** [comment]
Yah, I get it. it is complicated.
