### ISSUE TITLE
methodCollection discrete time prop

### ISSUE THREAD

**Issue by cmangat** [Big-Life-Lab/covid-19-wastewater#42]
methodCollection: method used to collect the data.
discTimeProp: Discrete time proportional
discTimeProp24hq1h: Discrete time proportional 24-hour composite, every 1 hr
discTimeProp24hq4h: Discrete time proportional 24-hour composite, every 4 hr
discTimeProp24hq6h: Discrete time proportional 24-hour composite, every 6 hr

The trigger time will vary.  For our hospital work it was was every 15 minutes.  I'm not sure what is going on with NWT, as they are handling that.  Also, the total integration time varies, in NWT is can be 48, to 72 hours.  So there needs to be some plasticity here.

**Comment by hswerdfe** [comment]
@cmangat  I think one extra field will do this `methodCollectionTriggerTime`  I suspect that the time portion of it can be done with start and end time of the sample.

**Comment by cmangat** [comment]
Sounds good, just need the input of an engineer.
