### ISSUE TITLE
Propose rotating the public health Information Details table

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#43]
I wonder if we should rotate the **CovidPublicHealthData** this would allow for different reporters of various information like hospital admition numbers and cases counts:
new proposed table would be
## CovidPublicHealthData
 
-   **publicHealthID**: (Primary key) Unique identifier for the table.

-   **ReporterID** ID of the reporter who gave this data

-   **PolygonID**: Links with the `Polygon` table (foreign key).

-   **date**: Date of covid-19 measure.

-   **dateType**: Type of date used.

    -   `episodeDate` : Episode date is usually just the earliest of a list of dates available as not every case has every date
    -   `onsetDate`: Earliest that symptoms were reported for this case
    -   `reportedDate`: Date that the numbers were reported publicly

-   **publicHealthMeasuretype**: Type of date used.

    -   `confirmed` :  Number of confirmed cases.
    -   `active`:Number of active cases.
    -   `tests`:Number Number of tests.
    -   `positiveTests`: Number of positive tests.
    -   `percentPositivityRate` Percent positivity rate.
    -   `hospitalCensus` Hospital census or the number of people admitted with covid-19.
    -   `hospitalAdmit` Hospital admissions or patients newly admitted to hospital.
-   **publicHealthMeasureValue**: numeric

-   **notes**: notes

**Comment by cmangat** [comment]
I think you need an Epi to look at this.  We have case data(individual people), with an associated date(s) -> mapped to datetype. So one case might have three associated dates to it, as you've outlined.   

The publichealthmeasure data are measures of groups of cases.  Is it appropriate that these are stored in the same table?  I'm not sure myself.  I can see how both of the above would be mapped to one or more polygons.  In a wide format would these two sets map to each other?

**Comment by hswerdfe** [comment]
good point. I know epi's I will ask an epi.

**Comment by DougManuel** [comment]
I use these data often. Tided up.
