### ISSUE TITLE
Approach to report variant assays

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/covid-19-wastewater#59]
What is the best approach to report variant levels?

**Comment by DougManuel** [comment]
From a public health perspective: proportion of sample from a VOC.
e.g. 2% B.1.17 of total viral copies.

**Comment by DougManuel** [comment]
See also #98.

**Comment by hswerdfe** [comment]
I don't think I understand this variant issue? Don't we just report on what ever fragments were found? and if we find fragment from the B.1.17 we just say that is the fragment and the concentration?

**Comment by DougManuel** [comment]
Currently we report gene regions — essentially PCR. Variant identification use a range of approaches. The current recommendation from the variant folks is to report presence of variants and proportion of variants.

I'll propose an approach on WWmeasure.

**Comment by rnaguru** [comment]
Agree with detect/non-detect flag and if former indicate proportion. This is based on detection of the "wild type" vs. Variant signature allele irrespective of the PCR assay type (primer extension or competition probe). By definition, the proportional number is internally normalized so no need for a fecal content marker such as PPMoV. 

Ct information is lost however when using a ratio...should that be reported? Wildtype vs. Variant allele CT's?

Target locus should be indicated in addition to, or in lieu of, Pangolin lineage as a variant may be captured by multiple signature loci.

**Comment by DougManuel** [comment]
@rnaguru We have had the suggestion of separately reporting Ct values for Wildtype AND variant. Recommendation to report these Ct values and not the proportion. 

Can you confirm that this approach makes sense? To not use proportion but report Ct values.

**Comment by DougManuel** [comment]
Could you explain this issue in more detail or provide a specific recommendation?

```Target locus should be indicated in addition to, or in lieu of, Pangolin lineage as a variant may be captured by multiple signature loci.```

**Comment by rnaguru** [comment]
> @rnaguru We have had the suggestion of separately reporting Ct values for Wildtype AND variant. Recommendation to report these Ct values and not the proportion. 
> 
> Can you confirm that this approach makes sense? To not use proportion but report Ct values.

I guess the question is what extra information is contained in raw Ct that isn't in ratios. Raw CT of individual replicates (3) could be reported which is a good thing as it gives an idea of how close to LOD one is and also of the general variability. For the ratio one has to use an average of the replicates for both the numerator and denominator. So information on variability is lost. 

In the spirit of conserving data granularity it might be better to report Ct. With the caveat that this value is not a value of absolute expression and therefore cannot be compared e.g. between days or labs.

**Comment by rnaguru** [comment]
> Could you explain this issue in more detail or provide a specific recommendation?
> 
> ```Target locus should be indicated in addition to, or in lieu of, Pangolin lineage as a variant may be captured by multiple signature loci.```

The Ct would have to be associated with an identifier of the allele and specifically the probe/primer set used. Not sufficient to say "b.1.1.7 assay". So based on the test we're using now. Report Ct with an identifier of D3 and another Ct with D3L identifier. The ratio of D3L/D3 would report proportional expression. 

This would account for a future scenario on which this mutation become part of another lineage and would no longer be specific to B.1.1.7. There will also be other assays that capture more than one variant (e.g. assays specific for N501Y). 

Does that make sense??

**Comment by DougManuel** [comment]
@rnaguru from our on-line discussion. Let's allow four different approaches. These approaches are the same as for gene regions.
1) presence -yes/no
2) proportion of variant to total virus
3) Ct - but with the cavaet that Ct values can't be compared over time -- same as gene regions.
4) copies/l - from a standardized curve.

OK?

**Comment by rnaguru** [comment]
Yes this is good. The ratio would be a single value, while Cts would be in triplicate.
