### ISSUE TITLE
how to record standard WWTP params

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#6]
how do we record standard WWTP parameters, like 
 * flow rate
 * TSS
 * BOD

two options 
1 in the measurements table change **genregion** to be **measurementCategory** and add some options to the possibilities like this. 
- **measurementCategory**: 
  - `covid-unspecified (default)`
  - `covid-N1`
  - `covid-N2`
  - `covid-N3`
  - `covid-E`
  - `covid-RdRp`
  - `covid-N1N2avg`
  - `ww-param-flow`
  - `ww-param-tss`
  - `ww-param-Bod`

**Comment by hswerdfe** [comment]
Option 2 create a separate table, with standard WW param data.

**Comment by DougManuel** [comment]
This fits best in the `Measurement` data. It could go in the `Sample` data, but `Sample`but better in `Measurement`. 
Your suggestion would work well if the `measureUnit` and `measureType` are generally the same as for gene regions, but I think they are not. 

If they are not, there are two options:
1 - change the name of `Measurement` to `geneMeasures` and then add `WWTPmeaures` or `WWTPParameters`.
2 - have new variables in `Measurement` that would be similar to the three gene region measures. 
`WWPara`, `WWParaUnit`, `WWParaMeasureType`, and `WWParaValue` .
The current `measureUnit` should then be changed to `geneUnit` and `measureType` to `geneMeasureType` and `measureValue` to `geneValue`. `geneRegion` would stay the same.

**Comment by hswerdfe** [comment]
We can expand the options for units as well and leave the measurement tables alone and the structure does not change at all, the main problem I see is that the list of **measurementCategory* and **measurementUnit**  might get a little long.

- **measurementUnit**: Unit of SARS-CoV-2 measurement.
  - `PMMoV`: Viral copies/copies PMMoV
  - `ml`:    Viral copies/mL
  - `gms`:   Viral copies/gm solids
  - `l`:     Viral copies/L
  - `crA`:   Viral copies/copies crAssphage
  - `m3_s`: meters cubed per second
  - `mg_l`:  milligrams  per liter
  - `mgO_l`: milligrams of oxygen per liter
  - `other`: Other measurement of viral copies. Also add `sampleUnitOther`.

if we don't do it this way I think I prefer your option 1, and have a `geneMeasurement`and `WWTPmeaurement` table.
