### ISSUE TITLE
Sample collection terminology

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/covid-19-wastewater#63]
The terminology that is currently being used for the sample collection method is not very clear to our research group. There seems to be a distinction between `grab`, `continuous`, `discrete` and `integrated`. Are the latter 3 all different composite samples, but what is there exact difference (any reference)? We are used to the terms `grab sample`, `composite sample - time proportional`, and `composite sample - flow proportional`.

- `grab sample`: Sample was a simple grab sample
- `contFlowProp`: Continuous flow proportional
- `contConstant`: Continuous constant time proportional?
- `contOther`: Continuous other
- `discTimeProp`: Discrete time proportional
- `discTimeProp24hq1h`: Discrete time proportional 24-hour composite, every 1 hr (make this more general)
- `discTimeProp24hq4h`: Discrete time proportional 24-hour composite, every 4 hr
- `discTimeProp24hq6h`: Discrete time proportional 24-hour composite, every 6 hr
- `discFlowProp`: Discrete flow proportional
- `discVolumeProp`: Discrete volume proportional
- `discOther`: Discrete other
- `integratedOther`: Integrated other

**Comment by DougManuel** [comment]
These terms came from a range of labs. @patrick-daoust can you help or provide clarity?

Let's reach out to a few labs.

**Comment by NielsNicolai** [comment]
Do you have any reference that provides more clarification to the terms you use? Because our labs are unfamiliar with these. Or could you improve the explanation, so that we better understand them and relate them to the terms we are familiar with i.e. `grab sample`, `composite sample - time proportional`, and `composite sample - flow proportional`.

**Comment by NielsNicolai** [comment]
Following the Ontario Template shared by @vipileggi from MECP, a distinction is made between:

- M1: compTimeProp24h - a composite time proportional 24-hour composite sample generally collected by an autosampler
- M2: compFlowProp24h - a composite flow proportional 24-hour composite sample generally collected by an autosampler
- M3: grabComp8h - a grab 8-hour composite with 8 grab samples taken once per hour, generally manually
- M4: grabComp3h - a grab 3-hour composite with 3 grab samples taken once per hour, generally manually
- M5: grabCompSample3 - a grab-composite sample composed of 3 separate grab samples (5L or more)
- M6: grabSample1 - a single large (10L or more) representative grab sample
- M7: grabPrimarySludge - a single large representative primary sludge sample following primary sedimentation at the WWTP without mixing of other sludge types 

How does this relate to the current collection methods?

**Comment by jaizkibel2** [comment]
> Following the Ontario Template shared by @vipileggi from MECP, a distinction is made between:
> 
> * M1: compTimeProp24h - a composite time proportional 24-hour composite sample generally collected by an autosampler
> * M2: compFlowProp24h - a composite flow proportional 24-hour composite sample generally collected by an autosampler
> * M3: grabComp8h - a grab 8-hour composite with 8 grab samples taken once per hour, generally manually
> * M4: grabComp3h - a grab 3-hour composite with 3 grab samples taken once per hour, generally manually
> * M5: grabCompSample3 - a grab-composite sample composed of 3 separate grab samples (5L or more)
> * M6: grabSample1 - a single large (10L or more) representative grab sample
> * M7: grabPrimarySludge - a single large representative primary sludge sample following primary sedimentation at the WWTP without mixing of other sludge types
> 
> How does this relate to the current collection methods?

Thank you. This is more in line with the data we are collecting at STC.

**Comment by DougManuel** [comment]
Let's use the above approach. We will flag for discussion the steering committee and others to ensure it works for everyone.

**Comment by NielsNicolai** [comment]
This issue was addressed in [commit](https://github.com/Big-Life-Lab/covid-19-wastewater/commit/a9130c0d467c7baf091d99a361446ce0990240be).

**Comment by vipileggi** [comment]
@DougManuel  and @NielsNicolai we've had some internal MECP discussions and we're planning to add Moore swab method to list of M1-M7 methods. Will be updating Ontario Template to reflect this later this weekend. 
> 'mooreSwab' (M8) to indicate Moore swab method to be used for presence-absence detection and potentially identify the need for quantitative sampling or  targeted diagnostic testing. Note addition for M8: Sampling method M8 is a presence-absence test and not considered quantitative at this time and only to be used to assess presence-absence."

**Comment by DougManuel** [comment]
Can you add to the proposed version v1.0

**Comment by vipileggi** [comment]
@DougManuel do I do that under Projects? Sorry not sure about the process. Will be adding the new Template as well.

**Comment by DougManuel** [comment]
Just add straight to the [metadata.md](https://github.com/Big-Life-Lab/covid-19-wastewater/blob/dev/metadata.md) file in the dev branch.

**Comment by vipileggi** [comment]
Ok thanks @DougManuel

**Comment by vipileggi** [comment]
@DougManuel and @NielsNicolai new Ontario Template (OT) with Moore swab option added (MECP internal discussion resolved that we include this option for reasons cited in Liu et al) to Sample worksheet and two new variables added to Measurement worksheet. A good ref. on using Moor swab [Liu et al](https://www.medrxiv.org/content/10.1101/2020.12.01.20238006v1.full.pdf). 
[Ontario_Template_ODM_1.0_Jan_25_2021.xlsx](https://github.com/Big-Life-Lab/covid-19-wastewater/files/5861311/Ontario_Template_ODM_1.0_Jan_25_2021.xlsx). Tried to upload OT on the Template subfolder and did not have write privileges to do that.

**Comment by NielsNicolai** [comment]
Great addition @vipileggi! In Quebec, we will also be performing Moore swabs for the long-term care facilities. Here's [another reference ](https://pubmed.ncbi.nlm.nih.gov/32332133/) which provides some additional background for the test.

**Comment by NielsNicolai** [comment]
Hi @vipileggi, note that in the upcoming version I did not add M7: grabPrimarySludge in the list of options. The reason here is that this option is in fact a combination of 'how the sample is collected' (sample_collection) and 'what kind of sample is collected' (sample_type). 

Therefore a better way would be to use the variable `sample_collection` = grabSample; and the variable `sample_type` = primarySludge.

Do you agree?

**Comment by vipileggi** [comment]
Hi @NielsNicolai, ok but we will need to change the single drop-down list (below) in the Ontario Template (OT) to two drop-down lists. That is fine and can do that in the OT once the ODM names are rectified. 
![SampleDropDownList](https://user-images.githubusercontent.com/74632605/105752730-aa3cdf00-5f15-11eb-8f29-447e9092afec.jpg)

**Comment by DougManuel** [comment]
Agree with removing `grabPrimarySludge`.

The steering committee didn't have a comment on this list. Let's go with what we've got.
