### ISSUE TITLE
Allow access to data

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/covid-19-wastewater#64]
Currently, all data access permisions are part of the reporter. This means that whenever a single reporter wants to share both data that is (i) visible to all (ii) and data that has access limitations, multiple instances of the same reporter will need to be created in the database. Which does not seem to be very efficient. Would it therefore not be better to have all the `allowAcces` fields on the level of the measurement (or sample)?

**Comment by DougManuel** [comment]
Yes, I agree. 

@hswerdfe (who is away) created this approach. I _think_ it replicates the approach used by PHAC for their covid-19 case report data. 

Let's modify as you state. Could you make this modification?

ODM follows the FAIR data principle. Please identify that if data access permission is the default. meaning if permision field is missing, the data will be assumed to be publicly shared.

**Comment by NielsNicolai** [comment]
The modifications were done as discussed with this [commit](https://github.com/Big-Life-Lab/covid-19-wastewater/commit/ece0311293c31aba32bf725301e1e436ce161c5e).

The ERD is also updated on LucidChart.
