### ISSUE TITLE
assayMethod.version

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/covid-19-wastewater#65]
Note that if you would update the `assayMethod.version` field (because of and improvement made to the assay and thus leading to a new version), all measurements that were performed in the past will also be linked to the updated version of the assay method. And thus they will loose their history. In fact the same applies to `AssayMethod.date`, `Lab.updateDate` 

Moreover, because the AssayMethod table does not have a `name` field, it is currently imposible to see that two versions of the same assay method exist.

**Comment by DougManuel** [comment]
The `AssayMethod` could use improvement. However, I don't follow your comment.

A new `AssayMethod` record would be created if there are modifications. The wouldn't be a rewrite of this table, rather an additional record. It could be that most fields would be the same. Absolutely, a historic measurement should not have a change to its historic assay method.

I agree that there could be `name` and `description` fields. However, there is an `id` and `version` which should be uniquely identifying. I will add those.

**Comment by DougManuel** [comment]
`description` already existed. Also added `alaisID`.
