### ISSUE TITLE
Reporting a new measurement

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/covid-19-wastewater#66]
Currently the `Reporter` is linked to the `Measurement` via the `Site`. This means that: if for some reason the person reporting for a certain site changes, a new site record has to be created (the only difference being the `reporter.ID` field). Does it not make more sense to link `Reporter` directly to the `Measurement` he/she is actually reporting on?

**Comment by DougManuel** [comment]
I agree we don't need a `Reporter.ID` for `Site`. Also agree that `Reporter` should be in `Measurement`. 

@NielsNicolai  could you make those changes? I think that you are currently modifying the ERD and could incorporate these changes in to the metadata and ERD.

**Comment by NielsNicolai** [comment]
This is resolved in this [commit ](https://github.com/Big-Life-Lab/covid-19-wastewater/commit/66ed9a5117cb2aa733568c8f7b781a1af8296db1)
The ERD on LucidChart is adjusted accordingly.
