### ISSUE TITLE
Field name conventions

### ISSUE THREAD

**Issue by nick-gibb** [Big-Life-Lab/covid-19-wastewater#7]
Field names here don't always follow database conventions: https://github.com/Big-Life-Lab/covid-19-wastewater/blob/main/metadata.md

E.g. see https://launchbylunch.com/posts/2014/Feb/16/sql-naming-conventions/

Specifically we could:
- convert all names to lowercase 
- separate words with underscores 

This is trivial, I know (feel free to ignore+close). But wanted to note anyway! :)

**Comment by DougManuel** [comment]
We've been trying to use camelCase. I reviewed what naming convention has been used internationally in the field. There wasn't a lot of consistency, but this seems most common. Also fairly common in other metadata standards.

We had database names as snake_case because commonly used in R, which appears to be the most common language for this field and it is also a standard in python.

**Comment by hswerdfe** [comment]
should we change? I am good with either case structure. you did mention R and I do use the `janitor` package in R which by default converts to snake case.

**Comment by DougManuel** [comment]
I suggest we keep as camelCase. camelCase is the most used approach across metadata standards and should work well with `janitor` or other packages. 

An additional consideration is the ability to create wide tables from long tables. People will want wide tables. 

A common wide format will use measureCat, measureUnit and measureType, with the value from measureValue. For example, for consider the following entry (see https://github.com/Big-Life-Lab/covid-19-wastewater/commit/b4069d9c1cb746fef9a4f478897d0a3df965c32f for commit at the time of writing):

measureCat = covidN1
measureUnit = PPMoV
measureTyep = sampleMean
measureValue = 42

Would become:
covidN1_PPMoV_sampleMean = 42
or
covidN1-PPMoV-sampleMean = 42

This could work with snake case or other approach but keeping the name parsimonious and camelCase helps in this situation. 

This
