### ISSUE TITLE
dot notation for Table.attribute

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/covid-19-wastewater#75]
I am just checking in whether we are ok with the `.` notation for Table.attribute.

1) I've tried to avoid `.` in variable names because this is not variable valid naming in all programming languages.

Also, 

2) suggest that we change the link key documentation from current `sample.ID` to `Sample.ID`.  We are using capital letter for table.

**Comment by DougManuel** [comment]
The typical rule for names in most languages follows: 

`The first character must be an English letter (A, B, C, . . ., Z) or underscore (_). Subsequent characters can be letters, numeric digits (0, 1, . . ., 9), or underscores.`

Let's follow the above approach. Some languages (SAS) still have a maximum length (32 for SAS).

**Comment by DougManuel** [comment]
Address by changing `.` to `__`.

**Comment by DougManuel** [comment]
@NielsNicolai `.` isn't going to work. See this issue. 

I agree that `__` isn't great. What about about a `_`. The tables have capital case, which helps differentiate from other variables.

**Comment by DougManuel** [comment]
Discussion with @NielsNicolai and @vincepillgi. 
1) Any key variable is unique. i.e. `measureID`.
2) Ok to have other attributes that are not unique i.e. `notes`, `description`, `dateTime`. 
     - when non-unique attributes in wide table use Table name `_` attribute name. ie. `Measure_notes`
3) `Table_` not needed if the attribute is unique, even in wide table format.

**Comment by NielsNicolai** [comment]
This issue is resolved in this [commit](https://github.com/Big-Life-Lab/covid-19-wastewater/commit/b6473c933a4b3fe049f69072b5f2d5f7b1e26e3b) following the suggestion made in the previous post of @DougManuel.
