### ISSUE TITLE
Derived variable and wide table formatted variables are long

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/covid-19-wastewater#79]
Users have restrictions on variable label character length. 31??

i.e. `wwtpSanitaryMunicipal_envTemperature_rangeHighestValue`

Discussing with @vincepileggi and @NielsNicolai, suggest truncating to 7 characters for categories. This will reduce readability of names. 

Variable names will also be reduced, when variables are combined, with combining with tables names or other variable names.

**Comment by vipileggi** [comment]
Hi @DougManuel  noticed the '.' being used for wide names; is this being replaced or just left over?
![wideVariable](https://user-images.githubusercontent.com/74632605/105901598-982d7000-5feb-11eb-8d32-a8f04ec78227.jpg)

**Comment by DougManuel** [comment]
Yes, left over. I'll correct.
