### ISSUE TITLE
Begin a Collaboration with the CDC

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/covid-19-wastewater#8]
I have been told the CDC already did a lot of this data model work, we need to find a contact to discuss with them.

**Comment by hswerdfe** [comment]
this is just resources :
presentation by CDC on Data  : https://cste.sharefile.com/share/view/s552abc13bbc436d8

data and reporting page from CDC :: https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/wastewater-surveillance/data-reporting-analytics.html

**Comment by DougManuel** [comment]
Let's bring this up with the PHAC covid-19 WW modelling group.

**Comment by hswerdfe** [comment]
we have a meeting now, that counts as a start. closing issue
