### ISSUE TITLE
Default variable name convention

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/covid-19-wastewater#90]
The following variables have an error, I believe.

They should have a lower case first letter and a `_`. e.g. `SampleTypeDefault` should be `sample_TypeDefault`.

Just checking if you agree before we make a first breaking change to V1.0.0. The correction would trigger an update to V1.0.1.

SampleTypeDefault: Used as default when a new sample is created for this site. See type in Sample table.

SampleTypeOtherDefault: Used as default when a new sample is created for this site. See typeOther in Sample table.

SampleCollectionDefault: Used as default when a new sample is created for this site. See collection in Sample table.

SampleCollectOtherDefault: Used as default when a new sample is created for this site. See collectionOther in Sample table.

SampleStorageTempCDefault: Used as default when a new sample is created for this site. See storageTempC in Sample table.

MeasureFractionAnalyzedDefault: Used as default when a new measurement is created for this site. See fractionAnalyzed in Measurement table.

**Comment by NielsNicolai** [comment]
I agree with the proposed names

**Comment by DougManuel** [comment]
I've updated to simply change to a lowercase first character to be consistent with other existing variables. 

e.g. `SampleCollectionDefault` —> `sampleCollectionDefault`. 

I didn't change to `sample_collectionDefault` because this would be a larger breaking change. However, that may be more appropriate to update everything to this format. Thoughts?

**Comment by DougManuel** [comment]
Addressed in c7d91128886cc93fdd680f0874a4d2861f52f4d6.
