### ISSUE TITLE
Name change for AssayMethod__sampleSizeL

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/covid-19-wastewater#92]
In the AssayMethod there exists a field `sampleSizeL` that is used to describe the amount of sample used in the assay. From what I understand, this is the extraction volume used in the assay. Is that correct? If so, would it not make sense to rename it to `extractionVolML` expressed in mL (which makes more sense than L).

**Comment by DougManuel** [comment]
This wold be a small breaking change. OK? @NielsNicolai

**Comment by NielsNicolai** [comment]
Yes it would. But it would make things more understandable for the lab folks. Do we agree?

**Comment by NielsNicolai** [comment]
`extractionVolMl`

**Comment by NielsNicolai** [comment]
Done in with this [commit](https://github.com/Big-Life-Lab/covid-19-wastewater/commit/fe41e884516e798ecde28a1e89c8a618f6154f2c)
