### ISSUE TITLE
Sample reporter 

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/covid-19-wastewater#93]
The person reporting a sample is not necessarily the same as the person providing the measurement analysis result. Therefore I would suggest adding the `reporterID` field also to the Sample table. Makes sense?

**Comment by vipileggi** [comment]
@DougManuel  @NielsNicolai I agree and makes sense to maintain a link between Sample and Reporter tables. I would recommend we proceed with this change.

**Comment by jeandavidt** [comment]
This issue is closed, but `reporterID` is not in the columns list for the table `Sample` in `variables.csv`
Can this be patched directly in `main`?

**Comment by DougManuel** [comment]
Yes, just make a hot fix to main.

**Comment by jeandavidt** [comment]
Done!
