### ISSUE TITLE
Aggregation types: meaning of "Normalized" (question)

### ISSUE THREAD

**Issue by jeandavidt** [Big-Life-Lab/covid-19-wastewater#99]
In the WWSample table and the SiteSample tables, a few of the aggregation types have the suffix 'Nr' (short for "Normalized"). But I'm not clear on what normalized means in this context. What is the data normalized against? Are normalization methods described somewhere in the data model, or is just one method expected? If so, how is it done?

Thanks! :)

**Comment by hswerdfe** [comment]
I suspect there might have been some confusion around this.
I believe originally the term Normal was introduced months ago to indicate if the sample was normalized by the pepper virus.

@jeandavidt  I agree it does not seem clear in this context what exactly this means.

**Comment by DougManuel** [comment]
There is likely confusion. Let's check with lab folks and correct, if needed for next update.

**Comment by vipileggi** [comment]
@jeandavidt seems to me like the aggregation options were a cut and pasted from WWMeasure table. Definitely, agree that there is no field normalization and  suggest that it does not apply and '*Nr' options should be removed.

**Comment by NielsNicolai** [comment]
@vipileggi Indeed these options were copy/pasted from the `WWMeasure` table. Should I remove them? @DougManuel @hswerdfe

**Comment by hswerdfe** [comment]
@vipileggi  I think I agree with removing them

**Comment by DougManuel** [comment]
Confirmed to remove from variables.

**Comment by NielsNicolai** [comment]
Done in this [commit](https://github.com/Big-Life-Lab/covid-19-wastewater/commit/4af2d21af978e454d8f2779d3806b8ccb50cb0b4)
